server:
  port: 9090

spring:
  boot:
    admin:
      ui:
        public-url: https://spring.nowstart.org:443/admin
        external-views:
          - label: "API 문서"
            url: "https://spring.nowstart.org/admin/swagger-ui/index.html"
            order: 1000
            iframe: true