server:
  port: 9090

spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "API 문서"
            order: 100
            url: "https://spring.nowstart.org/admin/swagger-ui/index.html"
            iframe: true
          - label: "모니터링"
            order: 101
            children:
              - label: "Grafana"
                url: "https://grafana.nowstart.org"
                iframe: true
              - label: "RabbitMQ"
                url: "https://rabbitmq.nowstart.org"
                iframe: true
              - label: "phpMyAdmin"
                url: "https://dsm.nowstart.org/phpmyadmin/"
                iframe: true